import { TBook } from "../../types";

export const booksArray: TBook[] = [
  {
    name: "Война и мир",
    author: "Л.Н. Толстой",
    year: "1873",
    genre: "роман-эпопея",
    id: "11233461",
    index: 1,
  },
  {
    name: "Война и мир",
    author: "Л.Н. Толстой",
    year: "1873",
    genre: "роман-эпопея",
    id: "11233415",
    index: 2,
  },
  {
    name: "Война и мир",
    author: "Л.Н. Толстой",
    year: "1873",
    genre: "роман-эпопея",
    id: "11233414",
    index: 3,
  },
  {
    name: "Война и мир",
    author: "Л.Н. Толстой",
    year: "1873",
    genre: "роман-эпопея",
    id: "11233413",
    index: 4,
  },
  {
    name: "Война и мир",
    author: "Л.Н. Толстой",
    year: "1873",
    genre: "роман-эпопея",
    id: "11233412",
    index: 5,
  },
  {
    name: "Война и мир",
    author: "Л.Н. Толстой",
    year: "1873",
    genre: "роман-эпопея",
    id: "11233411",
    index: 6,
  },
  {
    name: "Война и мир",
    author: "Л.Н. Толстой",
    year: "1873",
    genre: "роман-эпопея",
    id: "1123341",
    index: 7,
  },
];
