import { TBook } from "../../types";

export const booksArray: TBook[] = [
  {
    name: "Война и мир",
    author: "Л.Н. Толстой",
    year: "1869",
    genre: "роман-эпопея",
    id: "43572891",
    index: 1,
  },
  {
    name: "Преступление и наказание",
    author: "Ф.М. Достоевский",
    year: "1866",
    genre: "роман",
    id: "92738465",
    index: 2,
  },
  {
    name: "Мастер и Маргарита",
    author: "М.А. Булгаков",
    year: "1966",
    genre: "роман",
    id: "18273645",
    index: 3,
  },
  {
    name: "Отцы и дети",
    author: "И.С. Тургенев",
    year: "1862",
    genre: "роман",
    id: "56473829",
    index: 4,
  },
  {
    name: "Ревизор",
    author: "Н.В. Гоголь",
    year: "1836",
    genre: "комедия",
    id: "83927461",
    index: 5,
  },
  {
    name: "Евгений Онегин",
    author: "А.С. Пушкин",
    year: "1833",
    genre: "роман в стихах",
    id: "67483920",
    index: 6,
  },
  {
    name: "Герой нашего времени",
    author: "М.Ю. Лермонтов",
    year: "1840",
    genre: "роман",
    id: "91827364",
    index: 7,
  },
];
